Withdraw command is enabled

diff --git a/scripts/wallet_withdraw_rewards b/scripts/wallet_withdraw_rewards
--- a/scripts/wallet_withdraw_rewards
+++ b/scripts/wallet_withdraw_rewards
@@ -1,86 +1,118 @@
 #!/bin/bash
 
-source /scripts/functions/check_balance
+# Init vars
+source "${SRC_DIR}/functions/check_balance"
+source "${SRC_DIR}/functions/check_pool_registration"
+source "${SRC_DIR}/functions/wait_for_pool_registration"
+source "${SRC_DIR}/functions/wait_for_slot"
+source "${SRC_DIR}/functions/wait_for_sync"
 
 WALLET=$1
 TIMESTAMP=$(date +%s)
 
-if [ -z "$WALLET" ]; then
-    echo "Invalid wallet."
-    MISSING_ARG=1
-fi
+# Enter staking directory
+stakingDir="${WORK_DIR}/${CARDANO_NETWORK}-staking"
+mkdir -p wallets/${rewardWallet}/transactions
 
-if [ -n "$MISSING_ARG" ]; then
-    exit
+if [ -z "$name" ]; then
+	export name="main"
 fi
 
 # Check for required files
-if [ ! -f "${NODE_PATH}/staking/wallets/${WALLET}/payment.skey" ]; then
-    echo "Missing required payment.skey. You need to run \`generate_wallet ${WALLET}\` to generate this key."
-    MISSING_FILES=1
+if [ ! -f "${WORK_DIR}/wallets/${name}/payment.addr" ]; then
+	echo "Missing required payment.skey. You need to run \`wallet generate --name=${name}\` to generate this key."
+	exit 3 #TODO $ERROR_CODE_MISSING
 fi
 
-if [ ! -f "${NODE_PATH}/staking/wallets/${WALLET}/payment.addr" ]; then
-    echo "Missing required payment.addr. You need to run \`generate_wallet ${WALLET}\` to generate this key."
-    MISSING_FILES=1
+# Check for required files
+if [ ! -f "${WORK_DIR}/wallets/${name}/payment.addr" ]; then
+    echo "Missing required payment.addr. You need to run \`wallet create --name ${name}\` to generate this key."
+    echo "Or use \`--name wallet_name\` to select an existed wallet."
+    exit 3 #TODO $ERROR_CODE_MISSING
 fi
 
-if [ ! -f "${NODE_PATH}/staking/wallets/${WALLET}/stake.addr" ]; then
-    echo "Missing required stake.addr. You need to run \`generate_wallet ${WALLET}\` to generate this key."
-    MISSING_FILES=1
+	
+
+if [ ! -f "${WORK_DIR}/wallets/${name}/stake.addr" ]; then
+    echo "Missing required stake.addr. You need to run \`wallet generate --name=${WALLET}\` to generate this key."
+    exit 3 #TODO $ERROR_CODE_MISSING
 fi
 
-if [ ! -f "${NODE_PATH}/staking/wallets/${WALLET}/stake.skey" ]; then
-    echo "Missing required stake.skey. You need to run \`generate_wallet ${WALLET}\` to generate this key."
-    MISSING_FILES=1
+if [ ! -f "${WORK_DIR}/wallets/${name}/stake.skey" ]; then
+    echo "Missing required stake.skey. You need to run \`wallet generate --name=${WALLET}\` to generate this key."
+    exit 3 #TODO $ERROR_CODE_MISSING
 fi
-
-if [ -n "$MISSING_FILES" ]; then
-    exit
-fi
-
-cd ${NODE_PATH}/staking/wallets/${WALLET}/
-mkdir -p transactions/
 
 # Wait for node to sync
 if [[ "${WAIT_FOR_SYNC}" == "True" ]]; then
     wait_for_sync 99.90
 fi
 
-cardano-cli query protocol-parameters \
-    ${NETWORK_ARGUMENT} \
-    --out-file ${NODE_PATH}/staking/protocol.json
 
-ADDRESS=$(cat payment.addr)
-STAKE_ADDRESS=$(cat stake.addr)
-REWARD_BALANCE=$(cardano-cli query stake-address-info ${NETWORK_ARGUMENT} --address $(cat stake.addr) | jq -r ".[0].rewardAccountBalance")
+docker run --interactive \
+    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
+    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
+    --volume "${stakingDir}:/root" \
+    --workdir /root \
+    genzbank/cardano-cli \
+    query protocol-parameters \
+        ${NETWORK_ARGUMENT} \
+        --out-file protocol.json
+
+
+ADDRESS=$(cat "wallets/${rewardWallet}/payment.addr")
+STAKE_ADDRESS=$(cat "wallets/${rewardWallet}/stake.addr")
+
+REWARD_BALANCE=$(docker run --interactive \
+    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
+    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
+    --volume "${stakingDir}:/root" \
+    --workdir /root \
+    genzbank/cardano-cli \
+    query stake-address-info \
+        ${NETWORK_ARGUMENT} \
+        --address $STAKE_ADDRESS | jq -r ".[0].rewardAccountBalance")
 check_balance 200000 # Dummy transaction fee
 
 # Draft transaction
 echo "Draft transaction"
-cardano-cli transaction build-raw \
-    --tx-in "${UTXO}#${TXIX}" \
-    --tx-out ${ADDRESS}+0 \
-    --withdrawal ${STAKE_ADDRESS}+${REWARD_BALANCE} \
-    --ttl 0 \
-    --fee 0 \
-    --out-file transactions/tx.${TIMESTAMP}.draft
+docker run --interactive \
+    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
+    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
+    --volume "${WORK_DIR}/wallets:/wallets" \
+    --volume "${stakingDir}:/root" \
+    --workdir /root \
+    genzbank/cardano-cli \
+    transaction build-raw \
+        --tx-in "${UTXO}#${TXIX}" \
+        --tx-out ${ADDRESS}+0 \
+        --withdrawal ${STAKE_ADDRESS}+${REWARD_BALANCE} \
+        --ttl 0 \
+        --fee 0 \
+        --out-file /wallets/transactions/tx.${TIMESTAMP}.draft
 
 echo "Calculate fee"
-FEE=$(cardano-cli transaction calculate-min-fee \
-    --tx-body-file transactions/tx.${TIMESTAMP}.draft \
-    --tx-in-count 1 \
-    --tx-out-count 1 \
-    ${NETWORK_ARGUMENT} \
-    --witness-count 1 \
-    --byron-witness-count 0 \
-    --protocol-params-file ${NODE_PATH}/staking/protocol.json | tr ' ' '\n' | head -1)
+FEE=$(docker run --interactive \
+    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
+    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
+    --volume "${WORK_DIR}/wallets:/wallets" \
+    --volume "${stakingDir}:/root" \
+    --workdir /root \
+    genzbank/cardano-cli \
+    transaction calculate-min-fee \
+        --tx-body-file /wallets/transactions/tx.${TIMESTAMP}.draft \
+        --tx-in-count 1 \
+        --tx-out-count 1 \
+        ${NETWORK_ARGUMENT} \
+        --witness-count 1 \
+        --byron-witness-count 0 \
+        --protocol-params-file protocol.json | tr ' ' '\n' | head -1)
 
 # Find UTXO in address with enough lovelace to do the transaction
 check_balance ${FEE}
 
 # Update slot and TTL
-SLOT=$(get_slot)
+SLOT=$("${SRC_DIR}/relay_get_slot")
 TTL=$(expr ${SLOT} + 500)
 
 # Display transaction info
@@ -98,35 +130,36 @@ echo "Lovelace after withdrawal: ${BALANCE_AFTER_TX}"
 #
 # Create the transaction
 #
-cardano-cli transaction build-raw \
-    --tx-in "${UTXO}#${TXIX}" \
-    --tx-out ${ADDRESS}+${BALANCE_AFTER_TX} \
-    --withdrawal ${STAKE_ADDRESS}+${REWARD_BALANCE} \
-    --ttl ${TTL} \
-    --fee ${FEE} \
-    --out-file transactions/tx.${TIMESTAMP}.raw
-
-cardano-cli transaction sign \
-    --tx-body-file transactions/tx.${TIMESTAMP}.raw \
-    --signing-key-file payment.skey \
-    --signing-key-file stake.skey \
-    ${NETWORK_ARGUMENT} \
-    --out-file transactions/tx.${TIMESTAMP}.signed
-
-# Submit the transaction
-read -n 1 -r -s -p $'Press enter to submit the transaction...\n'
-
-echo "Submit transaction"
-OUT=$(cardano-cli transaction submit \
-    --tx-file transactions/tx.${TIMESTAMP}.signed \
-    ${NETWORK_ARGUMENT} 2>&1)
-
-if [[ $OUT =~ "Error" ]]
-then
-    echo "An error occoured."
-    echo ${OUT}
-    read
-else
-    echo "Transaction has been submitted to the blockchain."
-    echo ${OUT}
-fi
+#cardano-cli transaction build-raw \
+#    --tx-in "${UTXO}#${TXIX}" \
+#    --tx-out ${ADDRESS}+${BALANCE_AFTER_TX} \
+#    --withdrawal ${STAKE_ADDRESS}+${REWARD_BALANCE} \
+#    --ttl ${TTL} \
+#    --fee ${FEE} \
+#    --out-file transactions/tx.${TIMESTAMP}.raw
+#
+#cardano-cli transaction sign \
+#    --tx-body-file transactions/tx.${TIMESTAMP}.raw \
+#    --signing-key-file payment.skey \
+#    --signing-key-file stake.skey \
+#    ${NETWORK_ARGUMENT} \
+#    --out-file transactions/tx.${TIMESTAMP}.signed
+#
+## Submit the transaction
+#read -n 1 -r -s -p $'Press enter to submit the transaction...\n'
+#
+#echo "Submit transaction"
+#OUT=$(cardano-cli transaction submit \
+#    --tx-file transactions/tx.${TIMESTAMP}.signed \
+#    ${NETWORK_ARGUMENT} 2>&1)
+#
+#if [[ $OUT =~ "Error" ]]
+#then
+#    echo "An error occoured."
+#    echo ${OUT}
+#    read
+#else
+#    echo "Transaction has been submitted to the blockchain."
+#    echo ${OUT}
+#fi
+#
